### ISSUE TITLE
Latest in Pypi?

### ISSUE THREAD

**Issue by andrewcooke** [benchling/sqlalchemy_batch_inserts#4]
Hi,

I'm using this library to load a pile of data from multiple threads and am hitting uniqueness violations on the primary key (joined table inheritance on the base table).  I'm using the version from Pypi, but I see that was released before the latest commit.  So I'm wondering if (1) you've also seen this issue (maybe it's expected and I should simply retry?) and (2) whether a new release would help?

It is, of course, also possible that there's some problem in my code - I am looking at that now.

Thanks, Andrew

**Comment by andrewcooke** [comment]
Oh, well, it's not even configured properly.  WIll close and re-open if it's still a problem.  Sorry for the noise.

**Comment by andrewcooke** [comment]
Hmmm.  My code works unless I enable your library. But I realise that's not proof.  I will try master and, if that also, fails, try to write a simple POC and re-open.

**Comment by andrewcooke** [comment]
As far as I can tell (and I am not 100% certain, but things work now and I have more important bugs to fix):

* The enable_batch_inserting(session) should be called once per engine (even though it takes a session and not an engine as an argument).

* If you call enable_batch_inserting() multiple times per engine, it gets called multiple times on session flush (yay).

* Multiple calls trigger some kind of error with inconsistent sequences across processes with the Pypi release, but not with master (maybe related to the commit in how sequences are retrieved from Postgres?)

* So my code sucks and your code works.

* But it would be nice if enable_batch_inserting() were idempotent.

And thanks - this seems to give me a significant speedup, even though my loading is spread across many processes and in fairly small chunks.

**Comment by vineetgopal** [comment]
Thanks for the information. I went ahead and updated to the latest version in PyPI, so you should be able to use that now!

As far as idempotency, the bug you ran into make sense to me. Unfortunately, I don't think there's a native way in SQLAlchemy to avoid the redundant event registration. One possibility is I could store a module-private cache of sessions/engines the event has been registered on – I'm going to hold off on doing this right now since the latest version does work for you, but if this continues to cause problems, let me know and I can look into it.

Glad to hear you saw a significant speed up :)

**Comment by andrewcooke** [comment]
Thanks, I am now using the latest.

I should also add, since the above may mislead someone else, that I eventually found the (real) bug in my code.  I had my own rapid insertion routine, similar to this library but less elegant, for another database engine (sqlite) and that was still being used at one point, which meant that additional IDs from a separate source were being added to the table, making the sequence generate values that led to conflicts.
